
ribbon:
  IsSecure: false


security:
  user:
    name: pd
    password: keepitsimple1

---

spring:
  profiles: pact

ribbon:
  eureka:
    enabled: false

hystrix:
  command:
    randomFortune:
      execution.isolation.thread.timeoutInMilliseconds: 2000

workshop:
  ribbon:
    listOfServers: localhost:8080
   
  
      
        
    
